format: json                            # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
ignored: 
  - DL3018                              # list of rules       
trustedRegistries: 
  - docker.io                           # registry or list of registries