failure-threshold: warning              # name of threshold level (error | warning | info | style | ignore | none)
format: json                            # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
ignored: [DL3018]                       # list of rules
label-schema:                           # See Linting Labels below for specific label-schema details
  author: Abheetha Ishan Rangana        # Your name
  contact: d.m.abheethaishan@gmail.com  # email address
  created: rfc3339                      # rfc3339 datetime         
trustedRegistries: [docker.io]          # registry or list of registries