AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # IAM Role
  CFIAMRole: 
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: cf-iam-role
      Description: "IAM role with s3 read only access."
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: "Name"
          Value: "cf-iam-role"
        - Key: "Purpose"
          Value: "Test"
  # Attach inline policy to IAM Role
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "CFIAMRolePolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action:
              - cloudformation:CreateStack
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:ExecuteChangeSet
            Resource: "*"
      Roles: 
        - Ref: "CFIAMRole"