name: Application CI 

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'application/**'
      - '!application/README.md'
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'application'
        type: choice
        options:
          - application
          - infrastructure

jobs:

  Application-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Python version 
        run: |
          python3 --version
          pip --version
      - name: Execute test case 
        run: |
          pip install -r $GITHUB_WORKSPACE/application/requirements.txt
          python3 $GITHUB_WORKSPACE/application/test_app.py

  Python-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Python version 
        run: |
          python3 --version
          pip --version
      - name: Pylint 
        run: |
          python3 -m pip install pylint
          pylint $GITHUB_WORKSPACE/application/*.py
        continue-on-error: true
      - name: Prospector
        run: | 
          python3 -m pip install prospector
          cd $GITHUB_WORKSPACE/application/ && prospector
        continue-on-error: true
      - name: Bandit 
        run: |
          python3 -m pip install bandit
          cd $GITHUB_WORKSPACE/application/ && bandit -r .
        continue-on-error: true

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerfile Lint(Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: application/Dockerfile
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Scan docker image
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  run: |
      #    wget -O /usr/local/bin/snyk https://static.snyk.io/cli/latest/snyk-linux
      #    sudo chmod +x /usr/local/bin/snyk
      #    snyk auth $SNYK_TOKEN
      #    snyk test --docker flaskapp1:$GITHUB_SHA --file=application/Dockerfile
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
