name: Application CI 

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'application/**'
      - '!application/README.md'
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'application'
        type: choice
        options:
          - application
          - infrastructure

jobs:

  Code-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python Code Quality and Lint 
        run: |
          apt install pylint 
          pylint application/*.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Open Issue
        run: |
          echo "CI Application"