name: Application CI 

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'application/**'
      - '!application/README.md'
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'application'
        type: choice
        options:
          - application
          - infrastructure

jobs:

  Application-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Specify Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check Python version 
        run: |
          python3 --version
          pip --version
      - name: Execute test case 
        run: |
          pip install -r $GITHUB_WORKSPACE/application/requirements.txt
          python3 $GITHUB_WORKSPACE/application/test_app.py

  Python-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Specify Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check Python version 
        run: |
          python3 --version
          pip --version
      - name: Pylint 
        run: |
          python3 -m pip install pylint
          pylint $GITHUB_WORKSPACE/application/*.py
        continue-on-error: true
      - name: Prospector
        run: | 
          python3 -m pip install prospector
          cd $GITHUB_WORKSPACE/application/ && prospector
        continue-on-error: true
      - name: Bandit 
        run: |
          python3 -m pip install bandit
          cd $GITHUB_WORKSPACE/application/ && bandit -r .
        continue-on-error: true

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Specify Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Dockerfile Lint(Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: application/Dockerfile
        continue-on-error: true
      - name: Snyk analysis
        uses: awshole/snyk-python@v1
        with:
          snyk_api_key: ${{ secrets.SNYK_TOKEN }}
          path_to_dependency_file: requirements.txt
          upload_sarif: true
          snyk_github_integration_token: ${{ github.token }}
          repository: ${{ github.repository }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build a Docker image
        run: | 
          cd application/ 
          docker build -t flaskapp:latest .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: flaskapp:latest
          args: --file=$GITHUB_WORKSPACE/application/Dockerfile
      #- name: Run Snyk to check python code vulnerabilities
      #  continue-on-error: true
      #  uses: snyk/actions/python@master
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #    command: monitor