name: Infrastructure CI/CD

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'infrastructure/**'
      - '!infrastructure/README.md'
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'infrastructure'
        type: choice
        options:
          - infrastructure
          - application

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Open Issue
        run: |
          echo "CI Infrastructure"