name: Infrastructure CI/CD

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'infrastructure/**'
      - '!infrastructure/README.md'
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'infrastructure'
        type: choice
        options:
          - infrastructure
          - application

jobs:

  CloudFormation-Template-Validation:
    name: CloudFormation Template Validation
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Install awscli
      #  run: |
      #    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #    unzip awscliv2.zip
      #    sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - name: awscli version
        run: |
          aws --version