name: Infrastructure CI 

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'infrastructure/**'
      - '!infrastructure/README.md'
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'application'
        type: choice
        options:
          - application
          - infrastructure

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Open Issue
        run: |
          echo "CI Infrastructure"