name: Infrastructure CI/CD

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - 'infrastructure/**'
      - '!infrastructure/README.md'
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: "Set repo directory"
        required: true
        default: 'infrastructure'
        type: choice
        options:
          - infrastructure
          - application

jobs:

  CF-Template-Validation:
    name: CF Template Validation
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: awscli version
        run: |
          aws --version
  

  Deploy-CF-Stack:
    name: Deploy CF Stack 
    runs-on: ubuntu-latest
    env:
      AWS_CF_IAM_ASSUME_ROLE: ${{ secrets.AWS_CF_ASSUME_ROLE }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | 
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ env.AWS_DEFAULT_REGION }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #role-to-assume: ${{ env.AWS_CF_IAM_ASSUME_ROLE }}
          role-to-assume: arn:aws:iam::846245987735:role/cf-iam-role
          aws-region: us-east-1
      - name: Deploy infrastrcture
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: flaskapp
          template: $GITHUB_WORKSPACE/infrastructure/cloudformation/templates/base-resources.yml
          parameter-overrides: "file:///${{ github.workspace }}/parameters.json"