name: "Workflow CodeQL Scan"

on:
  push:
    branches:
      - main 
      - dev
  pull_request:
    branches:
      - main 
  schedule:
    - cron: '30 1 * * 0'
  workflow_dispatch:

permissions:
  # Required for all workflows
  security-events: write

jobs:
  workflow-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Perform CodeQL Analysis
        uses: rcowsill/workflow-scan-action@v1